Repository j178/prek, pull requests merged in 2025-09, with the labels that each got.

#569 Disable renovate updating mise managed toolchains for CI
  .github/renovate.json5
Labels: internal

#578 Update project status
  README.md
Labels: documentation

#595 Support `prek install|install-hooks|hook-impl|init-template-dir` in workspace mode
  docs/workspace.md
  src/cli/hook_impl.rs
  src/cli/install.rs
  src/workspace.rs
  tests/common/mod.rs
  tests/hook_impl.rs
  tests/install.rs
  tests/list.rs
  tests/workspace.rs
Labels: enhancement

#598 Implement `pre-push` hook type
  src/cli/hook_impl.rs
  src/git.rs
  tests/hook_impl.rs
Labels: enhancement

#605 Implement `auto-update` in workspace mode
  src/cli/auto_update.rs
  src/workspace.rs
  tests/auto_update.rs
Labels: enhancement

#611 Improve hook install concurrency
  src/cli/install.rs
  src/cli/run/run.rs
  src/languages/pygrep/pygrep.rs
  src/store.rs
Labels: enhancement

#612 Add design about `Project and Hook Selection`
  docs/workspace.md
Labels: documentation

#625 Update README
  README.md
Labels: internal

#635 Disable some renovate managers
  .github/renovate.json5
Labels: internal

#638 Fix docker mount in workspace mode
  src/languages/docker.rs
  src/languages/docker_image.rs
  tests/languages/docker.rs
Labels: bug

#643 Use a rooster fork
  mise.toml
  pyproject.toml
Labels: internal

#646 Add a notice to rerun `prek install` when upgrading to 0.2.0
  CHANGELOG.md
Labels: documentation

#647 Add a warning to `hook-impl` when the script needs reinstall
  src/cli/hook_impl.rs
  src/cli/install.rs
  src/cli/mod.rs
  src/main.rs
  tests/install.rs
Labels: enhancement

#667 Add Codecov badge to README
  README.md
Labels: internal

#668 Run `setup python test` in the same job with `cargo test`
  .config/nextest.toml
  .github/workflows/ci.yml
Labels: ci

#669 Update README.md
  README.md
Labels: internal

#672 Ignore pty from code coverage
  .github/workflows/ci.yml
Labels: ci

#676 Bring back `.pre-commit-config.yml` support
  docs/diff.md
  lib/constants/src/lib.rs
  src/cli/auto_update.rs
  src/cli/hook_impl.rs
  src/cli/mod.rs
  src/config.rs
  src/hook.rs
  src/languages/node/version.rs
  src/languages/python/version.rs
  src/workspace.rs
  tests/auto_update.rs
  tests/common/mod.rs
  tests/install.rs
  tests/languages/script.rs
  tests/run.rs
  tests/sample_config.rs
  tests/validate.rs
Labels: enhancement

#677 Ignore config file from hidden directory
  docs/workspace.md
  src/workspace.rs
Labels: enhancement

#678 Add docs about builtin hooks
  README.md
  docs/builtin.md
  mkdocs.yml
Labels: documentation

#679 Add docs about TODOs
  README.md
  docs/index.md
  docs/todo.md
  mkdocs.yml
Labels: documentation

#683 Support selectors in `prek install/install-hooks/hook-impl`
  src/cli/hook_impl.rs
  src/cli/install.rs
  src/cli/mod.rs
  src/cli/run/mod.rs
  src/cli/run/run.rs
  src/cli/run/selector.rs
  src/main.rs
  tests/hook_impl.rs
  tests/install.rs
Labels: enhancement

#702 Add docs about debugging
  README.md
  docs/debugging.md
  docs/index.md
  docs/workspace.md
  mkdocs.yml
Labels: documentation

#705 Use bigger buffer for fixing trailing whitespace
  src/builtin/pre_commit_hooks/fix_trailing_whitespace.rs
Labels: enhancement

#708 Fix `trailing-whitespace` & `mixed-line-ending` write file path
  src/builtin/pre_commit_hooks/fix_trailing_whitespace.rs
  src/builtin/pre_commit_hooks/mixed_line_ending.rs
  src/cli/run/run.rs
  src/git.rs
  tests/builtin_hooks.rs
Labels: bug

#723 fix: support py38 for pygrep
  src/languages/pygrep/script.py
Labels: bug

#724 Enable more aggressive optimizations for release
  Cargo.toml
Labels: performance

#725 Enable go mod cache for faster go related tests
  .github/workflows/ci.yml
Labels: ci

#727 Fix typo in language-version to language_version
  docs/diff.md
Labels: documentation

#728 Update benchmarks
  README.md
  docs/assets/bench-disk.png
  docs/assets/bench.png
  docs/benchmark.md
Labels: documentation

#745 Update some docs
  docs/builtin.md
  docs/configuration.md
  docs/diff.md
Labels: documentation

#731 Use concurrent read and write in `git check-attr`
  src/builtin/pre_commit_hooks/check_added_large_files.rs
  src/git.rs
Labels: bug

#766 Add support for specifying `PREK_UV_SOURCE`
  .github/workflows/ci.yml
  Cargo.toml
  docs/configuration.md
  lib/constants/src/env_vars.rs
  src/languages/python/uv.rs
Labels: enhancement

#779 Use `fs-err` wrapper for `File::lock`
  src/fs.rs
Labels: enhancement

#781 Clarify built-in hooks activation conditions and behavior
  docs/builtin.md
Labels: documentation

#789 Improve arg parsing for builtin hooks
  src/builtin/pre_commit_hooks/check_added_large_files.rs
  src/builtin/pre_commit_hooks/fix_trailing_whitespace.rs
  src/builtin/pre_commit_hooks/mixed_line_ending.rs
  tests/builtin_hooks.rs
Labels: enhancement

#790 Support `--allow-multiple-documents` for `check-yaml`
  src/builtin/pre_commit_hooks/check_yaml.rs
  src/builtin/pre_commit_hooks/mod.rs
Labels: enhancement

#791 Run docker container with `--init`
  src/languages/docker.rs
Labels: enhancement

#793 Add PaperQA2 to "Who is using prek"
  README.md
Labels: documentation

#795 Add `prek cache dir`, move `prek gc` and `prek clean` under `prek cache`
  docs/cli.md
  docs/diff.md
  src/cli/clean.rs
  src/cli/mod.rs
  src/main.rs
  tests/cache.rs
  tests/clean.rs
  tests/common/mod.rs
  tests/run.rs
Labels: enhancement

#800 Add a hint when hooks failed in CI
  lib/constants/src/env_vars.rs
  src/cli/run/run.rs
  tests/run.rs
Labels: enhancement

#806 Add `--dry-run` to `prek auto-update`
  docs/cli.md
  src/cli/auto_update.rs
  src/cli/mod.rs
  src/main.rs
  tests/auto_update.rs
Labels: enhancement

#807 Show error message in quiet mode
  docs/cli.md
  src/cli/mod.rs
  src/cli/run/run.rs
  src/main.rs
  src/printer.rs
  tests/run.rs
Labels: enhancement

#809 Update document
  docs/builtin.md
  docs/configuration.md
Labels: internal

#798 Implement hook health check
  src/cli/run/run.rs
  src/hook.rs
  src/languages/docker.rs
  src/languages/docker_image.rs
  src/languages/fail.rs
  src/languages/golang/golang.rs
  src/languages/mod.rs
  src/languages/node/node.rs
  src/languages/pygrep/pygrep.rs
  src/languages/python/mod.rs
  src/languages/python/python.rs
  src/languages/script.rs
  src/languages/system.rs
  src/store.rs
  tests/languages/node.rs
  tests/languages/pygrep.rs
Labels: enhancement
