Repository j178/prek, pull requests merged in 2025-08, with the labels that each got.

#299 Simplify npm installing dependencies
  src/languages/node/node.rs
Labels: enhancement

#300 Update readme
  README.md
Labels: documentation

#302 Rename `autoupdate` to `auto-update`, `init-templatedir` to `init-template-dir`
  src/cli/mod.rs
Labels: enhancement

#305 Use more `anyhow::Context`
  src/languages/node/installer.rs
  src/languages/python/python.rs
Labels: internal

#306 Parse `entry` when constructing hook
  src/builtin/pre_commit_hooks/check_added_large_files.rs
  src/builtin/pre_commit_hooks/fix_trailing_whitespace.rs
  src/hook.rs
  src/languages/docker.rs
  src/languages/docker_image.rs
  src/languages/fail.rs
  src/languages/node/node.rs
  src/languages/python/python.rs
  src/languages/script.rs
  src/languages/system.rs
  tests/run.rs
Labels: enhancement

#307 Improve hook invalid error message
  src/config.rs
  src/hook.rs
  tests/run.rs
Labels: enhancement

#310 Improve error message for hook installation and run
  src/cli/run/run.rs
  src/hook.rs
  src/languages/docker.rs
  src/languages/docker_image.rs
  src/languages/fail.rs
  src/languages/mod.rs
  src/languages/node/node.rs
  src/languages/python/python.rs
  src/languages/script.rs
  src/languages/system.rs
  tests/languages/fail.rs
  tests/languages/main.rs
  tests/languages/python.rs
  tests/languages/unimplemented.rs
Labels: enhancement

#311 Fix `end-of-file-fixer` replaces `\r\n` with `\n`
  src/builtin/pre_commit_hooks/fix_end_of_file.rs
  tests/builtin_hooks.rs
Labels: bug

#313 Add `sample-config --file` to write sample config to file
  README.md
  lib/constants/src/env_vars.rs
  src/cli/mod.rs
  src/cli/sample_config.rs
  src/main.rs
  tests/sample_config.rs
Labels: enhancement, extended feature

#314 Improve `sample-config` writing file
  src/cli/install.rs
  src/cli/run/run.rs
  src/cli/sample_config.rs
  src/main.rs
Labels: enhancement

#316 Fix issue that `entry` of `pygrep` is not shell commands
  src/builtin/pre_commit_hooks/check_added_large_files.rs
  src/builtin/pre_commit_hooks/fix_trailing_whitespace.rs
  src/hook.rs
  src/languages/docker.rs
  src/languages/docker_image.rs
  src/languages/fail.rs
  src/languages/node/node.rs
  src/languages/python/python.rs
  src/languages/script.rs
  src/languages/system.rs
  src/run.rs
  tests/languages/main.rs
  tests/languages/pygrep.rs
  tests/run.rs
Labels: bug

#319 Cache computed `dependencies` on hook
  src/hook.rs
  src/languages/node/node.rs
Labels: enhancement

#321 Support `python311` as a valid language version
  src/languages/node/installer.rs
  src/languages/python/version.rs
  src/languages/version.rs
  tests/languages/python.rs
Labels: bug

#323 Cache the found path to uv
  src/languages/python/uv.rs
Labels: enhancement

#331 Minor improvement to `install_hooks`
  src/cli/run/run.rs
Labels: internal

#333 Use more `Arc<T>` over `Box<T>`
  src/cli/install.rs
  src/cli/run/run.rs
  src/hook.rs
  src/languages/docker.rs
  src/languages/docker_image.rs
  src/languages/fail.rs
  src/languages/mod.rs
  src/languages/node/node.rs
  src/languages/python/python.rs
  src/languages/script.rs
  src/languages/system.rs
Labels: performance

#335 Skipped hook name should be taken into account for columns
  src/cli/run/run.rs
  src/git.rs
Labels: bug

#338 Impl `FromStr` for language request
  src/cli/run/run.rs
  src/languages/node/installer.rs
  src/languages/node/mod.rs
  src/languages/node/node.rs
  src/languages/node/version.rs
  src/languages/python/python.rs
  src/languages/python/version.rs
  src/languages/version.rs
Labels: enhancement

#332 Fix large file check to use staged_get instead of intent_add
  src/builtin/pre_commit_hooks/check_added_large_files.rs
  tests/builtin_hooks.rs
  tests/common/mod.rs
Labels: bug

#345 Manage uv cache dir
  lib/constants/src/env_vars.rs
  src/languages/python/python.rs
  src/languages/python/uv.rs
  src/store.rs
Labels: enhancement

#346 Improve node support
  lib/constants/src/env_vars.rs
  src/languages/node/installer.rs
  src/languages/node/node.rs
Labels: enhancement

#350 Fix bug that directories are ignored
  src/cli/run/filter.rs
  tests/run.rs
Labels: bug, performance

#354 Add migration section to README
  README.md
Labels: documentation

#358 Add `--directory` to `prefligit run`
  README.md
  src/cli/hook_impl.rs
  src/cli/mod.rs
  src/cli/run/filter.rs
  src/cli/run/mod.rs
  src/cli/run/run.rs
  src/git.rs
  src/main.rs
  tests/run.rs
Labels: enhancement, extended feature

#360 Remove env_vars from hook run
  src/builtin/meta_hooks.rs
  src/builtin/mod.rs
  src/builtin/pre_commit_hooks/check_added_large_files.rs
  src/builtin/pre_commit_hooks/fix_end_of_file.rs
  src/builtin/pre_commit_hooks/fix_trailing_whitespace.rs
  src/builtin/pre_commit_hooks/mod.rs
  src/cli/run/run.rs
  src/languages/docker.rs
  src/languages/docker_image.rs
  src/languages/fail.rs
  src/languages/golang/golang.rs
  src/languages/mod.rs
  src/languages/node/node.rs
  src/languages/python/python.rs
  src/languages/script.rs
  src/languages/system.rs
Labels: internal

#362 Implement `tags_from_interpreter`
  src/cli/run/filter.rs
  src/identify.rs
Labels: enhancement

#363 Remove `normalize_output` test helper
  tests/builtin_hooks.rs
Labels: internal

#368 Fix cache dir permission before clean
  src/cli/clean.rs
Labels: bug

#374 Fix `npm install` on Windows
  src/languages/node/installer.rs
  tests/languages/node.rs
Labels: bug

#373 Add value hint to `prefligit run` flags
  src/cli/mod.rs
Labels: enhancement

#352 Check minimum supported version for uv found from system
  src/languages/python/uv.rs
Labels: enhancement

#381 Set `GOROOT` when installing golang hook
  lib/constants/src/env_vars.rs
  src/languages/golang/golang.rs
  src/languages/golang/installer.rs
  src/languages/node/installer.rs
  src/languages/python/python.rs
Labels: bug

#382 Improve language tests
  tests/common/mod.rs
  tests/languages/golang.rs
  tests/languages/node.rs
  tests/languages/python.rs
Labels: ci

#391 Fix identify tags for `Pipfile.lock`
  src/identify.rs
Labels: bug

#395 Pin uv version in CI
  .github/workflows/ci.yml
  src/languages/python/uv.rs
Labels: ci

#398 Fix `script` command path
  src/languages/script.rs
  tests/languages/main.rs
  tests/languages/script.rs
Labels: bug

#380 Add dynamic completion of hook ids
  Cargo.lock
  Cargo.toml
  src/cli/mod.rs
  src/main.rs
Labels: enhancement

#403 Make error message handling in tests more robust
  tests/languages/node.rs
  tests/languages/python.rs
  tests/run.rs
Labels: ci

#399 Avoid reading whole file into memory in `fix_end_of_file` and make it consistent with `pre-commit-hooks`
  src/builtin/pre_commit_hooks/fix_end_of_file.rs
Labels: performance

#410 Simplify `fix_end_of_file` a bit
  src/builtin/pre_commit_hooks/fix_end_of_file.rs
Labels: internal

#383 Implement `pygrep` language support
  README.md
  pyproject.toml
  src/builtin/pre_commit_hooks/check_added_large_files.rs
  src/languages/mod.rs
  src/languages/pygrep/mod.rs
  src/languages/pygrep/pygrep.rs
  src/languages/pygrep/script.py
  src/languages/python/mod.rs
  src/languages/python/python.rs
  src/languages/python/uv.rs
  src/store.rs
  tests/languages/pygrep.rs
Labels: enhancement

#415 Do not set `GOROOT` and `GOPATH` for system found go
  src/languages/golang/golang.rs
  src/languages/golang/installer.rs
Labels: enhancement

#419 Add a shortcut to run original pre-commit to check output
  lib/constants/src/env_vars.rs
  tests/common/mod.rs
Labels: ci

#420 Use `brew install j178/tap/prek` for now
  README.md
Labels: documentation

#422 Minor tweaks
  README.md
  src/cli/mod.rs
Labels: internal

#416 Implement `check_json` as built hook
  Cargo.lock
  src/builtin/pre_commit_hooks/check_json.rs
  src/builtin/pre_commit_hooks/mod.rs
  tests/builtin_hooks.rs
Labels: enhancement

#423 Support `prek run` multiple hooks
  DIFF.md
  src/cli/hook_impl.rs
  src/cli/mod.rs
  src/cli/run/run.rs
  src/main.rs
  tests/run.rs
Labels: enhancement

#426 Make `--to-ref` default to HEAD if `--from-ref` is specified
  src/cli/mod.rs
Labels: enhancement

#411 Refactor `fix_trailing_whitespace`
  .gitignore
  src/builtin/pre_commit_hooks/fix_trailing_whitespace.rs
Labels: performance

#437 Add check for `minimum_prek_version`
  src/config.rs
  src/hook.rs
  src/snapshots/prek__config__tests__read_config.snap
  src/snapshots/prek__config__tests__read_manifest.snap
  src/version.rs
  tests/run.rs
Labels: enhancement

#442 Calculate more accurate max cli length
  src/run.rs
Labels: bug

#450 Add warning for non-existent hook id
  src/cli/run/run.rs
  tests/run.rs
Labels: enhancement, error message

#453 Fix uv install on Windows
  src/languages/python/uv.rs
Labels: bug

#267 Add a job to test Python and uv setup
  .github/workflows/ci.yml
Labels: internal, ci

#462 Cleanup various code
  src/languages/python/uv.rs
  src/store.rs
Labels: internal

#466 Find `uv` alongside the `prek` binary
  src/languages/python/uv.rs
Labels: enhancement

#471 Run hooks with pty if color enabled
  Cargo.lock
  Cargo.toml
  src/cli/run/run.rs
  src/languages/docker.rs
  src/languages/docker_image.rs
  src/languages/golang/golang.rs
  src/languages/node/node.rs
  src/languages/python/python.rs
  src/languages/script.rs
  src/languages/system.rs
  src/main.rs
  src/process.rs
  src/pty/LICENSE
  src/pty/error.rs
  src/pty/mod.rs
  src/pty/pty.rs
  src/pty/sys.rs
  src/pty/types.rs
  src/run.rs
  tests/run.rs
Labels: enhancement

#473 Support `language_version: lts` for node
  src/languages/node/installer.rs
  src/languages/node/version.rs
Labels: enhancement

#474 Adjust `sample-config` file path before writing
  src/main.rs
  tests/sample_config.rs
Labels: bug

#475 Resolve script shebang before running
  src/builtin/pre_commit_hooks/check_added_large_files.rs
  src/builtin/pre_commit_hooks/fix_trailing_whitespace.rs
  src/hook.rs
  src/identify.rs
  src/languages/docker.rs
  src/languages/docker_image.rs
  src/languages/fail.rs
  src/languages/golang/golang.rs
  src/languages/mod.rs
  src/languages/node/node.rs
  src/languages/python/python.rs
  src/languages/script.rs
  src/languages/system.rs
  tests/run.rs
Labels: bug

#476 Refactor project constructure
  src/builtin/meta_hooks.rs
  src/cli/install.rs
  src/cli/list.rs
  src/cli/mod.rs
  src/cli/run/run.rs
  src/workspace.rs
  tests/run.rs
Labels: internal

#477 Don’t show the progress bar if there’s no need for cloning or installing hooks
  src/cli/mod.rs
  src/cli/reporter.rs
  src/cli/run/run.rs
  src/languages/docker.rs
  src/languages/docker_image.rs
  src/languages/fail.rs
  src/languages/golang/golang.rs
  src/languages/mod.rs
  src/languages/node/node.rs
  src/languages/pygrep/pygrep.rs
  src/languages/python/python.rs
  src/languages/script.rs
  src/languages/system.rs
  src/store.rs
  src/workspace.rs
Labels: enhancement

#478 Clone repo temporarily into scratch directory
  src/store.rs
Labels: enhancement

#479 Move GIT_ROOT to a LazyLock
  src/cli/mod.rs
  src/git.rs
  src/main.rs
  src/workspace.rs
Labels: internal

#496 Update renovate configuration
  .github/renovate.json5
Labels: internal

#521 Add check for missing hooks in new revision
  src/cli/auto_update.rs
  tests/auto_update.rs
Labels: enhancement

#525 Fix `language: script` entry join issue
  src/languages/mod.rs
  src/languages/script.rs
  tests/languages/script.rs
Labels: bug

#530 Fix Python hook stderr are not captured
  src/languages/python/python.rs
  tests/languages/python.rs
Labels: bug

#544 Fix `trailing-whitespace` cannot handle file contains invalid utf-8 data
  src/builtin/pre_commit_hooks/fix_trailing_whitespace.rs
Labels: bug

#546 Fix trailing-whitespace eol trimming
  src/builtin/pre_commit_hooks/fix_trailing_whitespace.rs
Labels: bug

#559 Fix CI workflow
  .github/workflows/ci.yml
Labels: ci

#562 Make metadata extract a trace log instead of warn
  src/hook.rs
Labels: internal

#563 Move `pty` to `lib`
  Cargo.lock
  Cargo.toml
  lib/pty/Cargo.toml
  lib/pty/LICENSE
  lib/pty/src/error.rs
  lib/pty/src/lib.rs
  lib/pty/src/pty.rs
  lib/pty/src/sys.rs
  lib/pty/src/types.rs
  mise.toml
  src/main.rs
  src/process.rs
Labels: internal

#557 Implement `check_yaml` as builtin hook
  src/builtin/mod.rs
  src/builtin/pre_commit_hooks/check_yaml.rs
  src/builtin/pre_commit_hooks/mod.rs
  tests/builtin_hooks.rs
Labels: enhancement

#564 fix: Implement `pre-commit-hooks:check-toml`
  src/builtin/pre_commit_hooks/check_toml.rs
  src/builtin/pre_commit_hooks/mod.rs
Labels: enhancement

#565 Add validation for file type tags
  src/config.rs
  src/identify.rs
Labels: enhancement, error message
